/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    XwyaHead: typeof import('./../components/xwya-head/index.vue')['default']
    XwyaPage: typeof import('./../components/xwya-page/index.vue')['default']
  }
}
